### ISSUE TITLE
Microsoft.IO.RecyclableMemoryStream 3.0.0 Crashes

### ISSUE THREAD

**Issue by rastreus** [TheAngryByrd/FSharp.Control.WebSockets#9]
`Microsoft.IO.RecyclableMemoryStream` is updated to 3.0.0. The call to `GetStream()` on [line 664](https://github.com/TheAngryByrd/FSharp.Control.WebSockets/blob/88eedc80513219e7e9c56fbcbc51e5e79ba7ec97/src/FSharp.Control.Websockets/FSharp.Control.Websockets.fs#L664) throws an unhandled exception of System.MissingMethodException:

```
info: object[0]
      Client has connected. They've been assigned socketId: { SocketId = d6401f4a-7926-41e5-aec8-0d3d76a34cbf }
fail: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
         at FSharp.Control.Websockets.ThreadSafeWebSocket.receiveMessageAsUTF8@664-6.Invoke(Unit unitVar)
         at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
         at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
      --- End of stack trace from previous location ---
         at Saturn.Channels.Invoke@109.MoveNext()
         at Giraffe.Middleware.Invoke@63-1.MoveNext()
```

### Additional Context

I am using this through Saturn [Channels](https://github.com/SaturnFramework/Saturn/blob/main/src/Saturn/Channels.fs), targeting .NET 8.0 (8.0.100).

The exception does **not** occur when `Microsoft.IO.RecyclableMemoryStream` is pinned to 2.3.2. From semver assumptions, it seems like `GetStream()` is not an available method for 3.0.0.

**Comment by TheAngryByrd** [comment]
Yeah, looks like `RecyclableMemoryStream` changed their API. Can you send a pull request for updating it?
